name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2.0]
        pg: [12, 13, 14, 15]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby == 'debug' }}
    env:
      DATABASE_URL: postgres://postgres:hunter2@localhost:5432/attr_vault

    services:
      postgres:
        image: postgres:${{ matrix.pg }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: hunter2
          POSTGRES_DB: attr_vault
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - run: bundle install
      - run: bundle exec rspec
